version: '3.1'

services:
    archiview:
        build:
            context: ./Backend/Archiview
        restart: on-failure
        container_name: archiview-server
        ports:
            - 11443:11443

    signaling-server:
        build:
            context: ./Backend/SignalingServer
        container_name: signaling-server
        restart: on-failure
        ports:
            - 12080:12080
            - 12443:12443
        environment:
            TZ: "Asia/Seoul"
            OPENVIDU_URL: [OPENVIDU_URL]
        volumes:
            - /opt/openvidu/recordings:/opt/openvidu/recordings
            - /opt/openvidu/profiles:/opt/openvidu/profiles
networks:
    default:
        external:
            name: openvidu_default
