spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: [데이터베이스 URL]
#    url: jdbc:mysql://localhost:3306/archiview?serverTimezone=Asia/Seoul
    username: [USER_ID]
    password: [USER_PASSWORD]

  jpa:
    # Hibernate가 실행한 모든 SQL을 출력
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # DB를 실행할 때, 기존의 DB를 지우고 새로 생성
      ddl-auto: update
    properties:
      hibernate:
        # 실행한 SQL의 가독성을 좋게 변환
        # format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: [GOOGLE_ID]
    password: [GOOGLE_KEY_VALUE]
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# redis
  data:
    redis:
      host: redis
#      host: 127.0.0.1
      port: 6379
#      password: ssafyb105

# jwt secret key
jwt:
  secret: 1Ak0LMGoQpMaTrq4yJKZWD14l9CwN+f9dIOR2cELfZc=

server:
  servlet:
    encoding:
      # response UTF-8 인코딩
      charset: UTF-8
      force: true
  port: 11443
  ssl:
    enabled: true
    key-store: classpath:/ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ssafyb105

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
